### ISSUE TITLE
any plan to open source the `src/main/resources/selenium-cucumber-methods-1.0.0.jar`

### ISSUE THREAD

**Issue by agilecreativity** [selenium-cucumber/selenium-cucumber-java#2]
Do you have any plan to include these classes as a standard Java files instead of compiled Java files?
This will make it possible for others to contribute or fix some bugs if any.

**Comment by sameer49** [comment]
The files are already present on github
https://github.com/selenium-cucumber/selenium-cucumber-java/tree/master/src/main

**Comment by agilecreativity** [comment]
Hi Sameer,
I think this file is not a Java files e.g. it is a compiled Java file https://github.com/selenium-cucumber/selenium-cucumber-java/blob/master/src/main/resources/selenium-cucumber-methods-1.0.0.jar

**Comment by sameer49** [comment]
sorry my mistake, please switch to dev branch.
https://github.com/selenium-cucumber/selenium-cucumber-java/tree/dev/src/main/java/methods

**Comment by agilecreativity** [comment]
Hi Sameer,

Thank you so much, now this all make sense ;)

@sameer49
