### ISSUE TITLE
when i am running the dreadful features am getting error 

### ISSUE THREAD

**Issue by sreedhar-ib** [selenium-cucumber/selenium-cucumber-java#8]
[error-log.txt](https://github.com/selenium-cucumber/selenium-cucumber-java/files/1047430/error-log.txt)

**Comment by sameer49** [comment]
@sreedhar-ib you have not set IE driver path in system variable.
download IE driver https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver and set into system path.
